//= YAML (De)Serializer
= Plain Scalar Scanning
:icons: font

== Examples

.Document Consisting Entirely of a Single-Line Plain Scalar
--
[cols=2]
|===
a|
[source, yaml]
----
foo bar fizz
----

a|
[source, json]
----
"foo bar fizz"
----
|===

Here, the root node of the document is determined to just be a plain scalar
value.  There is no additional content meaning, this YAML stream is valid.
--


.Document Consisting Entirely of a Multi-Line Plain Scalar
--
[cols=2]
|===
a|
[source, yaml]
----
foo bar
fizz


buzz
----

a|
[source, json]
----
"foo bar fizz\n\nbuzz"
----
|===
--

.Single-Line Plain Scalar Mapping Key
--
[cols=2]
|===
a|
[source, yaml]
----
foo bar:
----

a|
[source, json]
----
{
  "foo bar": null
}
----
|===
--

==== Single-Line Plain Scalar Mapping Value

[cols=2]
|===
a|
[source, yaml]
----
foo bar: fizz buzz
----

a|
[source, json]
----
{
  "foo bar": "fizz buzz"
}
----
|===


=== Invalid YAML

==== Multi-Line Plain Scalar Key

===== In a Flow Mapping

[cols=2]
|===
a|
[source, yaml]
----
{

   foo barr

fizz buzz

  :}
----

a|
[source, json]
----
{
  "foo bar\nfizz buzz": null
}
----
|===

In the flow context, we know once we see the start of a plain scalar value, that
the plain scalar value will not end until it reaches a colon (`:`) character,
a (`,`) character, or a closing curly brace (`}`) character.

===== In a Block Mapping

.Example 1: No Parent, With Indent
--
[cols=2]
|===
a|
[source, yaml]
----
foo bar
 fizz:
buzz:
----

a|
[source, json]
----
{
  "foo bar fizz: buzz": null
}
----
|===
--

.Example 2: No Parent, Without Indent
--
[cols=2]
|===
a|
[source, yaml]
----
foo bar
fizz:
buzz:
----

a|
[source, json]
----
{
  "foo bar fizz": null,
  "buzz": null
}
----
|===
--

.Example 3: Parent Mapping, With Indent
--
[cols=2]
|===
a|
[source, yaml]
----
foo: bar
 fizz:
buzz:
----

a|
[source, json]
----
{
  "foo": "bar fizz:",
  "buzz": null
}
----
|===
--

.Example 4: Parent